### ISSUE TITLE
Remove material-icons-extended dependency

### ISSUE THREAD

**Issue by eygraber** [timo-drick/compose_edge_to_edge_preview#2]
It's very large and if only a few icons are used from it they can be added into the project (using https://composeicons.com/).

**Comment by timo-drick** [comment]
I copied all used material icons to a file. But to be honest it feels a little bit wrong to do it. But i will also check if i could remove some other dependencies.
Thank you very much for the feedback. I am really also interested in feed back on using this lib.

**Comment by eygraber** [comment]
`material-icons-extended` is already causing issues (it is messing around with the `mergeExtDexDevDebug` task causing it to take over 10 minutes to run, when it used to take 1.5 minutes).
