### ISSUE TITLE
Add isDarkMode as a parameter to EdgeToEdgeTemplate

### ISSUE THREAD

**Issue by eygraber** [timo-drick/compose_edge_to_edge_preview#3]
This would allow overriding the value, e.g. for cases where the UI is dark regardless of what mode the system is in. It could still use `isSystemInDarkTheme` as the default, e.g.

```kotlin
isDarkMode: Boolean = isSystemInDarkTheme(),
```

**Comment by timo-drick** [comment]
Version 0.5.0 includes this as parameter.

**Comment by timo-drick** [comment]
Version 0.5.0 includes this as parameter.
